# Generated by Django 4.2.5 on 2023-09-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='Categoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
