# Generated by Django 4.2.5 on 2023-09-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='codigo_isbn',
            new_name='codigo',
        ),
    ]
