# Generated by Django 4.2.5 on 2023-09-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_codigo_isbn_juego_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='codigo',
            new_name='codigo_invent',
        ),
    ]
