# Generated by Django 4.2.5 on 2023-10-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_codigo_juego_codigo_invent'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
